vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("n", "<Leader>w", "<Cmd>w<CR>")
vim.keymap.set("n", "<Leader>q", "<Cmd>q<CR>")
vim.keymap.set({"n", "v"}, "<Leader>c", "\"+y")
vim.keymap.set("n", "<C-v>", "\"+p")
vim.keymap.set("i", "<C-v>", "<Esc>\"+pa")
vim.keymap.set("c", "<C-v>", "<C-r>\"")
